version: "3"
services:
  node-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "9090:9090"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - port=9090
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE}
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    ports:
      - 8080:8080
